### ISSUE TITLE
SyntaxError while running code from README

### ISSUE THREAD

**Issue by m0leynik** [cdump/evmole#8]
Hello,

Just tried to run the Python example from README and got an error:

```
python3 ./test.py
Traceback (most recent call last):
  File "/home/dev/src/evmole/./test.py", line 1, in <module>
    from evmole import function_arguments, function_selectors
  File "/home/dev/src/evmole/evmole/__init__.py", line 1, in <module>
    from .arguments import function_arguments
  File "/home/dev/src/evmole/evmole/arguments.py", line 6, in <module>
    from .evm.vm import UnsupportedOpError, Vm
  File "/home/dev/src/evmole/evmole/evm/vm.py", line 53
    def step(self) -> tuple[OpCode, int, *tuple[Any, ...]]:
                           ^
SyntaxError: expected ':'
```

test.py contents (copied from README):
```
from evmole import function_arguments, function_selectors

code = '0x6080604052348015600e575f80fd5b50600436106030575f3560e01c80632125b65b146034578063b69ef8a8146044575b5f80fd5b6044603f3660046046565b505050565b005b5f805f606084860312156057575f80fd5b833563ffffffff811681146069575f80fd5b925060208401356001600160a01b03811681146083575f80fd5b915060408401356001600160e01b0381168114609d575f80fd5b80915050925092509256'
print( function_selectors(code) )
# Output(list): ['2125b65b', 'b69ef8a8']

print( function_arguments(code, '2125b65b') )
# Output(str): 'uint32,address,uint224'
```

Environment:
Ubuntu 22.04.4 LTS
Python 3.10.12
evmole: 9f028053 (latest master for now)

Thanks in advance!

**Comment by cdump** [comment]
Hi, https://pypi.org/project/evmole/ : `Requires: Python <4.0, >=3.11`, so you need at least python 3.11

**Comment by m0leynik** [comment]
Yep, my fault. 
The given example works correctly being executed using Python 3.12.
Thanks one again!
